apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName:  welcome-app-pipelinerun-
spec:
  serviceAccountName: welcome-pipeline-sa
  pipelineRef:
    name: welcome-app-pipeline
  params:
    - name: GIT_REPO
      value: git@github.com:christianh814/welcome-app.git
    - name: GIT_REF
      value: master
    - name: IMAGE_DEST
      value: quay.io/redhatworkshops/welcome-app
    - name: SRC_DOCKERFILE
      value: Containerfile
    - name: DEPLOY_REPO
      value: git@github.com:christianh814/welcome-deploy.git
    - name: DEPLOY_REF
      value: main
    - name: DEV_OVERLAY_DIR
      value: dev
    - name: PROD_OVERLAY_DIR
      value: prod
  workspaces:
    - name: welcome-app-ws1
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: scratch
      emptyDir: {}
