apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: build-trigger
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  serviceAccountName: welcome-pipeline-sa
  bindings:
    - ref: build-trigger
  template:
     name: build-trigger
